server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: content
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres-content:5432/content
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbit
    port: 5672
    username: playboy
    password: hugh-hefner

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
