server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: content
  rabbitmq:
    host: localhost
    port: 5672
    username: playboy
    password: hugh-hefner

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
