variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

image: maven:latest

services:
  - name: rabbitmq:3
    alias: rabbit

stages:
  - validate
  - build
  - test

cache:
  paths:
    - .m2/repository
    - target

validate:
  stage: validate
  tags:
    - shared-fi

  script:
    - "mvn validate"

format:
  stage: validate
  tags:
    - shared-fi

  script:
    - "mvn spotless:check"

lint:
  stage: validate
  tags:
    - shared-fi

  script:
    - "mvn spotbugs:check"

build-gateway:
  stage: build
  tags:
    - shared-fi

  script:
    - "mvn compile --projects dev.cere:gateway"

build-content:
  stage: build
  tags:
    - shared-fi

  script:
    - "mvn compile --projects dev.cere:content"

build-recommendations:
  stage: build
  tags:
    - shared-fi

  script:
    - "mvn compile --projects dev.cere:recommendations"

build-reviews:
  stage: build
  tags:
    - shared-fi

  script:
    - "mvn compile --projects dev.cere:reviews"

test-gateway:
  stage: test
  tags:
    - shared-fi

  script:
    - "mvn test --projects dev.cere:gateway"

test-content:
  stage: test
  tags:
    - shared-fi
  services:
    - name: postgres:16
      alias: postgres-content
      variables:
        POSTGRES_DB: content
        PGPORT: 54321

  script:
    - "mvn test --projects dev.cere:content"

test-recommendations:
  stage: test
  tags:
    - shared-fi
  services:
    - name: postgres:16
      alias: postgres-recommendations
      variables:
        POSTGRES_DB: recommendations
        PGPORT: 54323

  script:
    - "mvn test --projects dev.cere:recommendations"

test-reviews:
  stage: test
  tags:
    - shared-fi
  services:
    - name: postgres:16
      alias: postgres-reviews
      variables:
        POSTGRES_DB: reviews
        PGPORT: 54324

  script:
    - "mvn test --projects dev.cere:reviews"
