variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

image: maven:latest

services:
  - name: rabbitmq:3
    alias: rabbit

stages:
   - validate
   - build
   - test

cache:
 paths:
   - .m2/repository
   - target

validate:
 stage: validate

 script:
   - "mvn validate"

format:
 stage: validate

 script:
   - "mvn spotless:check"

lint:
 stage: validate

 script:
   - "mvn spotbugs:check"

build-gateway:
 stage: build

 script:
   - "mvn compile --projects dev.cere:gateway"

build-content:
 stage: build

 script:
   - "mvn compile --projects dev.cere:content"

build-recommendations:
 stage: build

 script:
   - "mvn compile --projects dev.cere:recommendations"

build-reviews:
 stage: build

 script:
   - "mvn compile --projects dev.cere:reviews"

test-gateway:
 stage: test
 services:
  - name: docker:dind
    alias: docker
    command: [ "--tls=false" ]

 script:
   - "mvn test --projects dev.cere:gateway -Dspring.profiles.active=docker"

test-content:
  stage: test
  services:
    - name: postgres:16
      alias: postgres-content
      variables:
        POSTGRES_DB: content
    - name: docker:dind
      alias: docker
      command: [ "--tls=false" ]

  script:
    - "mvn test --projects dev.cere:content -Dspring.profiles.active=docker"

test-recommendations:
 stage: test
 services:
   - name: postgres:16
     alias: postgres-recommendations
     variables:
       POSTGRES_DB: recommendations
   - name: docker:dind
     alias: docker
     command: [ "--tls=false" ]

 script:
   - "mvn test --projects dev.cere:recommendations -Dspring.profiles.active=docker"

test-reviews:
 stage: test
 services:
   - name: postgres:16
     alias: postgres-reviews
     variables:
       POSTGRES_DB: reviews
   - name: docker:dind
     alias: docker
     command: [ "--tls=false" ]

 script:
   - "mvn test --projects dev.cere:reviews -Dspring.profiles.active=docker"
