variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - validate
  - build
  - test

cache:
  paths:
    - .m2/repository
    - target

validate:
  stage: validate
  tags:
    - shared-fi

  script:
    - "mvn validate"

build:
  stage: build
  tags:
    - shared-fi

  script:
    - "mvn compile"


test:
  stage: test
  tags:
    - shared-fi

  script:
    - "mvn test"
