name: movies
version: '3.8'

services:
  gateway:
    build:
      context: .
      args:
        - SERVICE=gateway
    restart: unless-stopped
    profiles: [all, gateway]
    ports:
        - "9000:8080"
    networks: [movies]

  content:
    build:
      context: .
      args:
        - SERVICE=content
    restart: unless-stopped
    profiles: [all, content]
    depends_on: [rabbit]
    ports:
      - "9001:8080"
    networks: [movies, content]

  postgres-content:
    image: postgres:16
    restart: unless-stopped
    profiles: [all, dependencies, content]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content
    ports:
      - "54321:5432"
    networks: [content]

  recommendations:
    build:
      context: .
      args:
        - SERVICE=recommendations
    restart: unless-stopped
    profiles: [all, recommendations]
    depends_on: [rabbit]
    ports:
      - "9003:8080"
    networks: [movies, recommendations]

  postgres-recommendations:
    image: postgres:16
    restart: unless-stopped
    profiles: [all, dependencies, recommendations]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recommendations
    ports:
      - "54323:5432"
    networks: [recommendations]

  reviews:
    build:
      context: .
      args:
        - SERVICE=reviews
    restart: unless-stopped
    profiles: [all, reviews]
    depends_on: [rabbit, postgres-reviews]
    ports:
      - "9004:8080"
    networks: [movies, reviews]

  postgres-reviews:
    image: postgres:16
    restart: unless-stopped
    profiles: [all, dependencies, reviews]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews
    ports:
      - "54324:5432"
    networks: [reviews]

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: cere.dev
    environment:
      RABBITMQ_DEFAULT_USER: playboy
      RABBITMQ_DEFAULT_PASS: hugh-hefner
    profiles: [all, dependencies, content, recommendations, reviews]
    ports:
      - "5672:5672"   # amqp
      - "15672:15672" # http
      - "15692:15692" # http/promethus
    networks: [movies]

networks:
  movies:
    driver: bridge
  content:
    driver: bridge
  recommendations:
    driver: bridge
  reviews:
    driver: bridge
