name: movies
version: '3.8'

services:
  gateway:
    build:
      context: .
      args:
        - SERVICE=gateway
    restart: unless-stopped
    profiles: [all, gateway, content, users, recommendations, reviews]
    ports:
        - "9000:8080"
    networks: [movies]

  content:
    build:
      context: .
      args:
        - SERVICE=content
    restart: unless-stopped
    profiles: [all, content]
    depends_on: [gateway, rabbit]
    ports:
      - "9001:8080"
    networks: [movies]

  users:
    build:
      context: .
      args:
        - SERVICE=users
    restart: unless-stopped
    profiles: [all, users]
    depends_on: [gateway, rabbit]
    ports:
        - "9002:8080"
    networks: [movies]

  recommendations:
    build:
      context: .
      args:
        - SERVICE=recommendations
    restart: unless-stopped
    profiles: [all, recommendations]
    depends_on: [gateway, rabbit]
    ports:
      - "9003:8080"
    networks: [movies]

  reviews:
    build:
      context: .
      args:
        - SERVICE=reviews
    restart: unless-stopped
    profiles: [all, reviews]
    depends_on: [gateway, rabbit]
    ports:
      - "9004:8080"
    networks: [movies]

  postgres:
    image: postgres:16
    restart: unless-stopped
    profiles: [all, dependencies]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: cere.dev
    environment:
      RABBITMQ_DEFAULT_USER: playboy
      RABBITMQ_DEFAULT_PASS: hugh-hefner
    profiles: [all, dependencies, content, users, recommendations, reviews]
    ports:
      - "5672:5672"   # amqp
      - "15672:15672" # http
      - "15692:15692" # http/promethus
    networks: [movies]

networks:
  movies:
    driver: bridge
