scrape_configs:
  - job_name: 'Metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['content:8080', 'users:8080', 'recommendations:8080', 'reviews:8080', 'gateway:8080']
