server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

services:
  content:
    uri: http://content:8080
  users:
    uri: http://users:8080
  recommendations:
    uri: http://recommendations:8080
  reviews:
    uri: http://reviews:8080
