server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://oidc.muni.cz/oidc/introspect
          client-id: d57b3a8f-156e-46de-9f27-39c4daee05e1
          client-secret: fa228ebc-4d54-4cda-901e-4d6287f8b1652a9c9c44-73c9-4502-973f-bcdb4a8ec96a

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
    oauth:
      client-id: 7e02a0a9-446a-412d-ad2b-90add47b0fdd
      client-secret: 48a2b2e3-4b2b-471e-b7b7-b81a85b6eeef22f347f2-3fc9-4e16-8698-3e2492701a89
      scopes:
        - test_read
        - test_write

services:
  content:
    uri: http://localhost:9001
  users:
    uri: http://localhost:9002
  recommendations:
    uri: http://localhost:9003
  reviews:
    uri: http://localhost:9004

management:
    endpoints:
        web:
            exposure:
                include: [ "info", "logs", "prometheus", "health", "metrics" ]
