server:
  address: localhost
  port: 9000

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

services:
  content:
    uri: http://localhost:9001
  users:
    uri: http://localhost:9002
  recommendations:
    uri: http://localhost:9003
  reviews:
    uri: http://localhost:9004