server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: reviews
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:54324/reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
