server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: reviews
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres-reviews:5432/reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: rabbit
    port: 5672
    username: playboy
    password: hugh-hefner

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger

messaging:
  queue:
    name: reviews
    exchange: reviews
    routing-key: reviews

management:
    endpoints:
        web:
            exposure:
                include: [ "info", "logs", "prometheus", "health", "metrics" ]
