openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:9003
  description: Generated server url
paths:
  /recommendations/{movieId}:
    get:
      tags:
      - recommendation-controller
      operationId: findById
      parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RecommendationDto'
components:
  schemas:
    RecommendationDto:
      type: object
      properties:
        recommendedMovies:
          type: array
          items:
            type: integer
            format: int64
